name: Update Data and Model (Replit Sync)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # every day at 8am UTC

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data/model automation
        run: |
          python scripts/automate_data_pipeline.py

      - name: Commit updated data/model
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/
          git commit -m "Automated data/model update [CI skip]" || echo "No changes"
          git push